"""add icp_profile table

Revision ID: 25c846fecbbe
Revises: 5c8e6dc1b32b
Create Date: 2026-07-10 13:12:13.910685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25c846fecbbe'
down_revision: Union[str, None] = '5c8e6dc1b32b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icp_profile',
    sa.Column('icp_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('industries', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('employee_min', sa.Integer(), nullable=True),
    sa.Column('employee_max', sa.Integer(), nullable=True),
    sa.Column('revenue_min_usd', sa.BIGINT(), nullable=True),
    sa.Column('revenue_max_usd', sa.BIGINT(), nullable=True),
    sa.Column('countries', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('technologies', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('buying_committee_personas', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('icp_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('icp_profile')
    # ### end Alembic commands ###
