"""create initial schema

Revision ID: 444cdbe2a9d3
Revises: 
Create Date: 2026-07-09 09:24:32.445645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '444cdbe2a9d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('zi_company_id', sa.BIGINT(), nullable=False),
    sa.Column('company_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=False),
    sa.Column('company_domain', sa.Text(), nullable=True),
    sa.Column('company_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('company_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('employee_range', sa.VARCHAR(length=50), nullable=True),
    sa.Column('revenue_usd', sa.BIGINT(), nullable=True),
    sa.Column('revenue_range', sa.VARCHAR(length=50), nullable=True),
    sa.Column('ownership_type', sa.Text(), nullable=True),
    sa.Column('founded_year', sa.VARCHAR(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('state', sa.VARCHAR(length=100), nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), nullable=True),
    sa.Column('continent', sa.VARCHAR(length=100), nullable=True),
    sa.Column('primary_industry', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('industries', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('twitter_url', sa.Text(), nullable=True),
    sa.Column('facebook_url', sa.Text(), nullable=True),
    sa.Column('total_funding_amount', sa.BIGINT(), nullable=True),
    sa.Column('recent_funding_amount', sa.BIGINT(), nullable=True),
    sa.Column('recent_funding_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('company_funding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('employee_growth', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('competitors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('technologies', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('products', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.CheckConstraint("ownership_type IN ('public', 'private', 'pe_backed')", name='company_ownership_type_check'),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('zi_company_id')
    )
    op.create_index('idx_company_domain', 'company', ['company_domain'], unique=False)
    op.create_index('idx_company_zi_id', 'company', ['zi_company_id'], unique=False)
    op.create_table('company_intent',
    sa.Column('intent_id', sa.Text(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('signal_score', sa.SmallInteger(), nullable=True),
    sa.Column('signal_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('recommended_contacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('intent_id')
    )
    op.create_index('idx_intent_company_id', 'company_intent', ['company_id'], unique=False)
    op.create_index('idx_intent_signal_date', 'company_intent', ['signal_date'], unique=False)
    op.create_index('idx_intent_signal_score', 'company_intent', [sa.text('signal_score DESC')], unique=False)
    op.create_index('idx_intent_topic', 'company_intent', ['topic'], unique=False)
    op.create_table('company_news',
    sa.Column('news_id', sa.Text(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('page_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('news_id')
    )
    op.create_index('idx_news_category', 'company_news', ['category'], unique=False)
    op.create_index('idx_news_company_id', 'company_news', ['company_id'], unique=False)
    op.create_index('idx_news_page_date', 'company_news', [sa.text('page_date DESC')], unique=False)
    op.create_table('company_scoop',
    sa.Column('scoop_id', sa.Text(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scoop_id')
    )
    op.create_index('idx_scoop_company_id', 'company_scoop', ['company_id'], unique=False)
    op.create_index('idx_scoop_published_date', 'company_scoop', [sa.text('published_date DESC')], unique=False)
    op.create_table('decision_maker',
    sa.Column('zi_person_id', sa.BIGINT(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('picture_url', sa.Text(), nullable=True),
    sa.Column('job_title', sa.Text(), nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), nullable=True),
    sa.Column('years_of_experience', sa.VARCHAR(length=50), nullable=True),
    sa.Column('persona', sa.Text(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('mobile_phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.CheckConstraint("persona IN ('chairman', 'board_member', 'founder', 'co_founder', 'ceo', 'president', 'coo', 'cfo', 'cto', 'cio', 'ciso', 'chief_ai_officer', 'chief_data_officer', 'chief_product_officer', 'chief_strategy_officer', 'chief_revenue_officer', 'chief_marketing_officer', 'chief_sales_officer', 'chro', 'general_counsel', 'evp', 'svp', 'vp_operations', 'vp_sales', 'director', 'managing_director', 'general_manager')", name='decision_maker_persona_check'),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('zi_person_id')
    )
    op.create_index('idx_dm_company_id', 'decision_maker', ['company_id'], unique=False)
    op.create_index('idx_dm_email', 'decision_maker', ['email'], unique=False)
    op.create_index('idx_dm_persona', 'decision_maker', ['persona'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_dm_persona', table_name='decision_maker')
    op.drop_index('idx_dm_email', table_name='decision_maker')
    op.drop_index('idx_dm_company_id', table_name='decision_maker')
    op.drop_table('decision_maker')
    op.drop_index('idx_scoop_published_date', table_name='company_scoop')
    op.drop_index('idx_scoop_company_id', table_name='company_scoop')
    op.drop_table('company_scoop')
    op.drop_index('idx_news_page_date', table_name='company_news')
    op.drop_index('idx_news_company_id', table_name='company_news')
    op.drop_index('idx_news_category', table_name='company_news')
    op.drop_table('company_news')
    op.drop_index('idx_intent_topic', table_name='company_intent')
    op.drop_index('idx_intent_signal_score', table_name='company_intent')
    op.drop_index('idx_intent_signal_date', table_name='company_intent')
    op.drop_index('idx_intent_company_id', table_name='company_intent')
    op.drop_table('company_intent')
    op.drop_index('idx_company_zi_id', table_name='company')
    op.drop_index('idx_company_domain', table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
