"""add trigger_definition and trigger_event tables

Revision ID: 4e41097fa3da
Revises: 25c846fecbbe
Create Date: 2026-07-13 15:55:30.064761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e41097fa3da'
down_revision: Union[str, None] = '25c846fecbbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trigger_definition',
    sa.Column('trigger_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('signal_types', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('signal_categories', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('trigger_id')
    )
    op.create_table('trigger_event',
    sa.Column('trigger_event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trigger_id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('notified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('detected_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signal.signal_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_id'], ['trigger_definition.trigger_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trigger_event_id'),
    sa.UniqueConstraint('trigger_id', 'signal_id', name='trigger_event_trigger_signal_key')
    )
    op.create_index('idx_trigger_event_company_id', 'trigger_event', ['company_id'], unique=False)
    op.create_index('idx_trigger_event_trigger_id', 'trigger_event', ['trigger_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trigger_event_trigger_id', table_name='trigger_event')
    op.drop_index('idx_trigger_event_company_id', table_name='trigger_event')
    op.drop_table('trigger_event')
    op.drop_table('trigger_definition')
    # ### end Alembic commands ###
