"""add signal and lead_score tables

Revision ID: 5c8e6dc1b32b
Revises: 444cdbe2a9d3
Create Date: 2026-07-09 17:39:17.380861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c8e6dc1b32b'
down_revision: Union[str, None] = '444cdbe2a9d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_score',
    sa.Column('lead_score_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('gate_check_1', sa.Boolean(), nullable=True),
    sa.Column('gate_check_2', sa.Boolean(), nullable=True),
    sa.Column('gate_check_3', sa.Boolean(), nullable=True),
    sa.Column('gate_check_4', sa.Boolean(), nullable=True),
    sa.Column('gate_check_5', sa.Boolean(), nullable=True),
    sa.Column('gate_passed', sa.Boolean(), nullable=True),
    sa.Column('gate_status', sa.Text(), nullable=True),
    sa.Column('d1_pain_acuity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('d2_ai_intent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('d3_economic_capacity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('d4_authority', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('d5_timing_catalyst', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('d6_solution_fit', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('d7_competitive', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('component_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('p_convert', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('expected_deal_value_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('lead_score', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('scored_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("gate_status IN ('active', 'nurture')", name='lead_score_gate_status_check'),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('lead_score_id'),
    sa.UniqueConstraint('company_id', name='lead_score_company_id_key')
    )
    op.create_table('signal',
    sa.Column('signal_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), server_default='zoominfo', nullable=True),
    sa.Column('original_source', sa.Text(), nullable=True),
    sa.Column('signal_type', sa.Text(), nullable=False),
    sa.Column('signal_category', sa.Text(), nullable=False),
    sa.Column('core_fact', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dollar_value_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('extraction_method', sa.Text(), server_default='rule_based', nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('is_action', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('m2_corroboration', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('m3_recency', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('m4_resourcing', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('signal_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('ingested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('scored_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('signal_id'),
    sa.UniqueConstraint('original_source', name='signal_original_source_key')
    )
    op.create_index('idx_signal_company_id', 'signal', ['company_id'], unique=False)
    op.create_index('idx_signal_signal_category', 'signal', ['signal_category'], unique=False)
    op.create_index('idx_signal_signal_type', 'signal', ['signal_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_signal_signal_type', table_name='signal')
    op.drop_index('idx_signal_signal_category', table_name='signal')
    op.drop_index('idx_signal_company_id', table_name='signal')
    op.drop_table('signal')
    op.drop_table('lead_score')
    # ### end Alembic commands ###
