"""scope decision_maker to organisation with surrogate PK

Revision ID: 61a068921d3b
Revises: baf990bcfa89
Create Date: 2026-07-15 13:40:13.042724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a068921d3b'
down_revision: Union[str, None] = 'baf990bcfa89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decision_maker', sa.Column('decision_maker_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))

    # Backfill organisation_id from the linked company before making it NOT NULL.
    op.add_column('decision_maker', sa.Column('organisation_id', sa.UUID(), nullable=True))
    op.execute(
        """
        UPDATE decision_maker
        SET organisation_id = company.organisation_id
        FROM company
        WHERE company.company_id = decision_maker.company_id
        """
    )
    op.alter_column('decision_maker', 'organisation_id', nullable=False)

    # Swap the primary key from zi_person_id (global) to the new surrogate
    # decision_maker_id - zi_person_id alone is no longer unique across
    # Organisations that happen to import the same ZoomInfo contact.
    op.drop_constraint('decision_maker_pkey', 'decision_maker', type_='primary')
    op.create_primary_key('decision_maker_pkey', 'decision_maker', ['decision_maker_id'])

    op.create_unique_constraint('decision_maker_org_zi_person_id_key', 'decision_maker', ['organisation_id', 'zi_person_id'])
    op.create_index('idx_dm_organisation_id', 'decision_maker', ['organisation_id'], unique=False)
    op.create_foreign_key(None, 'decision_maker', 'organisation', ['organisation_id'], ['organisation_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'decision_maker', type_='foreignkey')
    op.drop_index('idx_dm_organisation_id', table_name='decision_maker')
    op.drop_constraint('decision_maker_org_zi_person_id_key', 'decision_maker', type_='unique')
    op.drop_constraint('decision_maker_pkey', 'decision_maker', type_='primary')
    op.create_primary_key('decision_maker_pkey', 'decision_maker', ['zi_person_id'])
    op.drop_column('decision_maker', 'organisation_id')
    op.drop_column('decision_maker', 'decision_maker_id')
    # ### end Alembic commands ###
