"""add organisation, workspace, user, workspace_member tables and tenancy FKs

Revision ID: baf990bcfa89
Revises: 4e41097fa3da
Create Date: 2026-07-14 17:35:46.008359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baf990bcfa89'
down_revision: Union[str, None] = '4e41097fa3da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Fixed IDs for the backfilled default org/workspace that existing
# company/icp_profile/trigger_definition rows get assigned to.
DEFAULT_ORG_ID = '00000000-0000-0000-0000-000000000001'
DEFAULT_WORKSPACE_ID = '00000000-0000-0000-0000-000000000002'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation',
    sa.Column('organisation_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_name', sa.Text(), nullable=True),
    sa.Column('account_url', sa.Text(), nullable=True),
    sa.Column('account_logo_url', sa.Text(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('company_name', sa.Text(), nullable=False),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('legal_business_name', sa.Text(), nullable=True),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('sub_industry', sa.Text(), nullable=True),
    sa.Column('headquarters_location', sa.Text(), nullable=True),
    sa.Column('founded_year', sa.Text(), nullable=True),
    sa.Column('employee_count_range', sa.Text(), nullable=True),
    sa.Column('annual_revenue_range', sa.Text(), nullable=True),
    sa.Column('business_type', sa.Text(), nullable=True),
    sa.Column('company_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('organisation_id'),
    sa.UniqueConstraint('account_url')
    )
    op.create_table('app_user',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.organisation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('workspace',
    sa.Column('workspace_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('workspace_name', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.organisation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_table('workspace_member',
    sa.Column('workspace_member_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), server_default='member', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_member_id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='workspace_member_workspace_user_key')
    )

    # Backfill: create a default org + workspace so existing rows have
    # something valid to point at, then assign every existing row to it.
    op.execute(
        f"""
        INSERT INTO organisation (organisation_id, company_name, account_name)
        VALUES ('{DEFAULT_ORG_ID}', 'Default Organisation', 'Default Organisation')
        """
    )
    op.execute(
        f"""
        INSERT INTO workspace (workspace_id, organisation_id, workspace_name)
        VALUES ('{DEFAULT_WORKSPACE_ID}', '{DEFAULT_ORG_ID}', 'Default Workspace')
        """
    )

    op.add_column('company', sa.Column('organisation_id', sa.UUID(), nullable=True))
    op.execute(f"UPDATE company SET organisation_id = '{DEFAULT_ORG_ID}'")
    op.alter_column('company', 'organisation_id', nullable=False)
    op.drop_constraint('company_zi_company_id_key', 'company', type_='unique')
    op.create_unique_constraint('company_org_zi_id_key', 'company', ['organisation_id', 'zi_company_id'])
    op.create_index('idx_company_organisation_id', 'company', ['organisation_id'], unique=False)
    op.create_foreign_key(None, 'company', 'organisation', ['organisation_id'], ['organisation_id'], ondelete='CASCADE')

    op.add_column('icp_profile', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.execute(f"UPDATE icp_profile SET workspace_id = '{DEFAULT_WORKSPACE_ID}'")
    op.alter_column('icp_profile', 'workspace_id', nullable=False)
    op.create_index('idx_icp_profile_workspace_id', 'icp_profile', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'icp_profile', 'workspace', ['workspace_id'], ['workspace_id'], ondelete='CASCADE')

    op.add_column('trigger_definition', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.execute(f"UPDATE trigger_definition SET workspace_id = '{DEFAULT_WORKSPACE_ID}'")
    op.alter_column('trigger_definition', 'workspace_id', nullable=False)
    op.create_index('idx_trigger_definition_workspace_id', 'trigger_definition', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'trigger_definition', 'workspace', ['workspace_id'], ['workspace_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trigger_definition', type_='foreignkey')
    op.drop_index('idx_trigger_definition_workspace_id', table_name='trigger_definition')
    op.drop_column('trigger_definition', 'workspace_id')
    op.drop_constraint(None, 'icp_profile', type_='foreignkey')
    op.drop_index('idx_icp_profile_workspace_id', table_name='icp_profile')
    op.drop_column('icp_profile', 'workspace_id')
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_index('idx_company_organisation_id', table_name='company')
    op.drop_constraint('company_org_zi_id_key', 'company', type_='unique')
    op.create_unique_constraint('company_zi_company_id_key', 'company', ['zi_company_id'])
    op.drop_column('company', 'organisation_id')
    op.drop_table('workspace_member')
    op.drop_table('workspace')
    op.drop_table('app_user')
    op.drop_table('organisation')
    # ### end Alembic commands ###
